services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzSystems\EzPlatformAdminUi\EventListener\ContentProxyCreateDraftListener: ~

    EzSystems\EzPlatformAdminUi\Form\Processor\Content\AutosaveProcessor:
        arguments:
            $innerContentFormProcessor: '@ezplatform.content_forms.form_processor.content'
        tags:
            - { name: kernel.event_subscriber }
